Final_projektas/mystore/main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('brands/', views.brands, name='brands'),
    path('brands/<int:brand_id>', views.brand, name='brand'),
    path('products/', views.products, name='products'),
    path('products/<int:pk>', views.ProductDetailView.as_view(),name='product-detail'),
    path('product-reviews', views.ReviewListApi.as_view()),
    path('product-review/<int:product_id>',views.add_review, name='review'),
    path('search/', views.search, name='search'),
    path('ordered-items/', views.ordered_items, name='ordered-items'),
    path('profile/', views.profile, name='profile'),
    path('favorites/', views.favorites, name='favorites'),
    path('product/<int:product_id>/add-to-favorites/', views.add_to_favorites, name='add_to_favorites'),
    path('product_detail/<int:product_id>', views.product_detail, name='product_detail'),
]

Final_projektas/mystore/mystore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('main/', include('main.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='main/', permanent=True))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Final_projektas/mystore/main/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
import uuid
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from datetime import date
from django.utils import timezone

class Category(models.Model):
    name = models.CharField('Category name', max_length=200, help_text='Enter category')
    description = models.TextField('Description', max_length=2000, default='')

    class Meta:
        verbose_name_plural = 'categories'
        ordering = ('name',)

    def __str__(self):
        return self.name

class Product(models.Model):
    title = models.CharField(_('Title'), max_length=200)
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='product_creator')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default='images/default.png')
    price = models.FloatField()
    in_stock = models.BooleanField(default=True)
    quantity = models.IntegerField('Quantity', help_text='Item quantity', null=False)
    cover = models.ImageField('Cover', upload_to='covers', null=True)

    class Meta:
        verbose_name_plural = 'Products'
        # ordering = ('-created_at',)

    def __str__(self):
        return self.title

class Order(models.Model):
    title = models.CharField('Title', help_text='Title of the service', max_length=50, null=False)
    date = models.DateField('Date', help_text='Order\'s date', null=False)
    ordered_item = models.ForeignKey('Product', on_delete=models.CASCADE, null=False)
    quantity = models.IntegerField('Quantity', help_text='Item quantity', null=False)
    price = models.FloatField('Price', help_text='Order price')

    def __str__(self):
        return f'{self.ordered_item}x{self.quantity}({self.price})'

class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    image_url = models.URLField(blank=True)
    # image = models.ImageField(upload_to='images/', default='images/default.png')

class ProductReview(models.Model):
    product = models.ForeignKey('Product', on_delete=models.SET_NULL, null=True, blank=True)
    reviewer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField('Atsiliepimas', max_length=2000)
    
    # class Meta:
    #     verbose_name = "Review"
    #     verbose_name_plural = 'Reviews'
    #     ordering = ['-date_created']

    def __str__(self):
        return f'{self.product.title}'
    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(default="profile_pics/default.png", upload_to="profile_pics")

    def __str__(self):
        return f"{self.user.username} profile"

Final_projektas/mystore/main/forms.py
from .models import ProductReview
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class ProductReviewForm(forms.ModelForm):
    class Meta:
        model = ProductReview
        fields = ('content', 'product', 'reviewer',)
        widgets = {'product': forms.HiddenInput(), 'reviewer': forms.HiddenInput()}

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['photo']

Final_projektas/mystore/main/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponse
from .models import Category, Product, Order, Favorite, ProductReview
from .forms import ProductReviewForm, UserUpdateForm, ProfileUpdateForm
from django.views import generic
from django.core.paginator import Paginator
from django.db.models import Q
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib.auth.forms import User
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from django.views.generic.edit import FormMixin
from django.contrib.auth.decorators import login_required
from rest_framework import generics, permissions
from .serializers import ProductReviewSerializer

def search(request):
    query = request.GET.get('query')
    search_results = Product.objects.filter(Q(title__icontains=query) | Q(summary__icontains=query))
    return render(request, 'search.html', {'products': search_results, 'query': query})


def index(request):
    product_count = Product.objects.all().count()
    # available_instances_available = Instance.objects.filter(status='av').count()
    brand_count = Category.objects.all().count()
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1
    context = {
        'product_count': product_count,
        'brand_count': brand_count,
        'num_visits': num_visits,
    }
    return render(request, 'index.html', context=context)


@login_required
def add_review(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        review = ProductReview()
        review.product = product
        review.user = request.user
        review.text = request.POST['text']
        review.save()
    return render(request, 'product_list.html', {'product': product})


def brands(request):
    paginator = Paginator(Category.objects.all(), 2)
    page_number = request.GET.get('page')
    paged_brands = paginator.get_page(page_number)
    context = {
        'brands': paged_brands
    } 
    return render(request, 'brands.html', context=context)   


def brand(request, brand_id):
    brand = get_object_or_404(Category, pk=brand_id)
    context = {
        'brand': brand
    }
    return render(request, 'brand.html', context=context)


def products(request):
    products=Product.objects.all()
    data = {
        'products': products
    }
    return render(request, 'product_list.html', data)


class ProductListView(generic.ListView):
    model = Product
    paginate_by = 2
    template_name = 'product_list.html'
    ordering = ['-created_by']
    # queryset = Product.objects.filter(title='Title 1')
 
    # def get_queryset(self):
    #     return Product.objects.filter(title='Title 1')    
    
    # def get_context_data(self, **kwargs):
    #     context = super(ProductListView, self).get_context_data(**kwargs)
    #     context['data'] = 'random text'
    #     return context


class ProductDetailView(FormMixin, generic.DetailView):
    model = Product
    template_name = 'product_detail.html'
    paginate_by = 3
    form_class = ProductReviewForm
    ordering = ['-created_by']

    def get_success_url(self):
        return reverse('product', kwargs={'pk': self.object.id})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.product = self.object
        form.instance.reviewer = self.request.user
        form.save()
        return super(ProductDetailView, self).form_valid(form)


def ordered_items(request):
    ordered_items = Order.objects.all()
    context = {'ordered_items': ordered_items}
    return render(request, 'ordered_items.html', context)


def add_to_favorites(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    favorite = Favorite(user=request.user, product=product, image_url=product.image_url)
    favorite.save()
    return redirect('product_detail', product_id=product.id)


# def favorites(request):
#     favorites = Favorite.objects.filter(user=request.user)
#     return render(request, 'favorites.html', {'favorites': favorites})

def favorites(request):
    favorites = Favorite.objects.filter(user=request.user)
    context = {'favorites': favorites}
    return render(request, 'favorites.html', context)


def product_detail(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    is_favorite = Favorite.objects.filter(user=request.user, product=product).exists()
    return render(request, 'favorites.html', {'product': product, 'is_favorite': is_favorite})


class ProductCreateView(CreateView):
    model = Product
    fields = ['title', 'description', 'price']
    success_url = reverse_lazy('product_list')


@csrf_protect
def register(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        if password == password2:
            if User.objects.filter(username=username).exists():
                messages.error(request, f'Username {username} taken!')
                return redirect('register')
            else:
                if User.objects.filter(email=email).exists():
                    messages.error(request, f'User with this email {email} is already registered!')
                    return redirect('register')
                else:
                    User.objects.create_user(username=username, email=email, password=password)
                    messages.info(request, f'User {username} registered!')
                    return redirect('login')
        else:
            messages.error(request, 'Passwords do not match!')
            return redirect('register')
    return render(request, 'register.html')


class ReviewListApi(generics.ListAPIView):
    queryset = ProductReview.objects.all()
    serializer_class = ProductReviewSerializer
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(reviewer=self.request.user)


@login_required
def profile(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f"Profile updated")
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'profile.html', context)


@login_required
def view_profile(request):
    try:
        profile = request.user.profile
    except profile.DoesNotExist:
        profile = None
    return render(request, 'profile.html', {'profile': profile})

Final_projektas/mystore/main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
 <title>My site</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Raleway:wght@300;400;500;800&display=swap');
    </style>
</head>
<body>
  <header class="site-header">
    <nav class="navbar fixed-top navbar-expand-sm navbar-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse">☰</button> 
      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav ml-auto">
          <div class="col-sm-2">
            <div class="navbar-nav">
              {% if user.is_authenticated %}
              <li class="nav-item active"> <a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
              <!-- <li class="nav-item active"> <a class="navbar-brand" href="{% url 'brands' %}">Our Brands</a></li> -->
              <li class="nav-item active"> <a class="navbar-brand" href="{% url 'products' %}">Product selection</a></li>

              <li class="nav-item active"> <a class="navbar-brand" href="{% url 'favorites' %}">Favourites</a></li>
              <li class="nav-item active"> <a class="navbar-brand" href="{% url 'profile' %}">
                <svg class="bi bi-person" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z" clip-rule="evenodd"/>
                </svg>
              <li class="nav-item active"> <a class="navbar-brand">{{ user.username }}</a></li>
              <li class="nav-item active"> <a class="navbar-brand" href="{% url 'logout'%}?next=/main">Log out</a></li>
              {% else %}
                <li class="nav-item active"> <a class="navbar-brand" href="{% url 'login'%}?next={{request.path}}">Log in</a></li>
               
                <li class="nav-item"><a class="navbar-brand" href="{% url 'register'%}">Register</a></li>
            {% endif %}
            {% load i18n %}
              <div class="navbar-nav">
                <li>
                  <form action="{% url 'search' %}" method="get" class="form-inline my-2 my-md-0">
                  <input name="query" class="form-control" type="text" placeholder="Search">
                  </form>
                </li>
              </div>
            </div>
          </div>
        </ul>
      </div>
  </nav>
  
  <div class="img-div">
    <!-- <img class="home-pic1" src="{% static 'pictures/home_pic3.jpg' %}" alt="My Image"> -->
</div>
  </header>
  <br>
    <div class="main_content">
      <div class="col-sm-10">
        {% block content %}{% endblock %}</div>
    </div>
    <br>
    <br>
    <section class="bottom-menu">
      <div class="about">
        <nav class="navbar navbar-#497174 bg-#497174">
          <div class="container-fluid">
            <ul>
              <li><a class="navbar-brand" href="#">About</a></li>
              <li><a class="navbar-brand" href="#">Contact</a></li>
              <li><a class="navbar-brand" href="#">Terms of Use</a></li>
              <li><a class="navbar-brand" href="#">Privacy Policy</a></li>
            </ul>
            <div class="social">
              <img src="{% static 'pictures/facebook.png' %}" alt="social" class="d-inline-block align-text-top">
              <img src="/static/pictures/instagram.png" alt="social" class="d-inline-block align-text-top">
              <img src="/static/pictures/twitter.png" alt="social" class="d-inline-block align-text-top">
            </div>
        </div>
        </nav>
        <footer>© Your Website 2023. All Rights Reserved.</footer>
      </div>
    </section>
  <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" class="img-fluid" alt="Responsive image"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" class="img-fluid" alt="Responsive image"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"class="img-fluid" alt="Responsive image"></script>
   
</body>
</html>

Final_projektas/mystore/main/templates/brand.html
{% extends "base.html" %}

{% block content %}
<div class="container brand">
  <h1>brands</h1>
  {% for brand in brands %}
    <li>{{brands.name}}</li>
  {% endfor %}
</div>
<br><br><br>
{% endblock %}

Final_projektas/mystore/main/templates/brands.html
{% extends "base.html" %}
{% block content %}
<div class="container_brand">
    <div class="home_div">
        <h4>{{ brand.name }}</h4>
        <hr/>
        <p>{{ brand.description }}</p>
        </hr>
        </br>
        <h5>We have these {{  brand.name }} :</h5>
        {% for product in brand.books.all %}
        <li>{{ Product.category }}</li> 
        {% endfor %}
    </div>
</div>
<br><br><br><br><br>

{% endblock %}

Final_projektas/mystore/main/templates/favorites.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<div class="container_brand">
    <div class="home_div">
        <h1>Favorite Products</h1>
        {% if favorites %}
            <ul>
            {% for favorite in favorites %}
                <div class="card mb-4 shadow-sm">
                    <img src="{{ favorite.image_url }}" alt="{{ favorite.product.title }}">
                    <p class="card-text"><a href="{% url 'product_detail' favorite.product.id %}">{{ favorite.product.title }}</a></p>
            </div>
            {% endfor %}
            </ul>
        {% else %}
            <p>You have no favorite products yet.</p>
        {% endif %}
    </div>
</div>
{% endblock %}

Final_projektas/mystore/main/templates/index.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block content %}
<html>
<head></head>
<body>
<div class="container-index">
  <div class="home_div">
    <h2>We currently have:</h2>
    <ul>
      <li><strong>Brands:</strong> {{ brand_count }}</li>
      <li><strong>Clothing:</strong> {{ product_count }}</li>
    
    </ul>
  </div>
</div>
</body>
<br><br><br><br><br>
</html>
{% endblock %}

Final_projektas/mystore/main/templates/ordered_items.html
{% extends 'base.html' %}

{% block content %}
<h1>Ordered Items</h1>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Price</th>
            <th>Quantity</th>
        </tr>
    </thead>
    <tbody>
        {% for item in ordered_items %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.description }}</td>
            <td>{{ item.price }}</td>
            <td>{{ item.quantity }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

Final_projektas/mystore/main/templates/product_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <div class="container_brand">
    <div class="home_div">
      <div class="col-md-4">
        <h1>{{ product.title }}</h1>
        {% if product.cover_image %}
            <img src="{{ product.cover.url }}" class="card-img-top" alt="...">
          {% else %}
            <img src="{% static 'pictures/no-image.png' %}" class="card-img-top">
        {% endif %}
          <p><strong>Category:</strong> <a href="{% url 'product-detail' product.category.pk %}">{{ product.category }}</a></p>
          <p><strong>Brand:</strong> {{ product.created_by.all|join:", " }}</p>  
          <p><strong>Description:</strong> {{ product.description }}</p>
          <form action="{% url 'add_to_favorites' product.id %}" method="post">
            {% csrf_token %}
            <button type="submit">Add to favorites</button>
          </form>
          </br>
            <h4>Reviews:</h4>
            {% if product.productreview.all %}
              {% for review in product.productreview_set.all %}
                <strong>{{  review.reviewer  }}</strong>, <em>{{ review.date_created }}</em>
                <p>{{ review.content }}</p>
                <hr>
              {% endfor %}
            {% else %}
              <p>Product doesn't have reviews</p>
            {% endif %}
        </div>
          </br>
          {% if user.is_authenticated %}
          <div class="fieldWrapper">
            <hr> 
            <form action="" method="post">
              {% csrf_token %}
              {{ form.content }}
              <br>
              <input type="submit" value="Save">
            </form>
          </div>
    </div>
  </div>
  {% endif %}
{% endblock %}

Final_projektas/mystore/main/templates/product_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container_brand">
  <div class="home_div">
    <h1>Product list</h1>
    <!-- {% if products %} -->
    <div class="row">
      <!-- <div class="col-md-7 card card-body p-4"> -->
          {% for product in products %}
          <div class="col-md-4 d-flex align-items-stretch">
            <div class="card mb-4 shadow-sm">
                  {% if product.cover %}
                    <img src="{{ product.cover.url }}" class="card-img-top" alt="...">
                  {% else %}
                    <img src="{% static 'pictures/no-image.png' %}" class="card-img-top">
                  {% endif %}
              
              <p class="card-text"><a href="{% url 'product-detail' product.id %}">{{product.title}} </a></p>
              <p>{{product.category}}</p>
              <p>{{product.price}}</p>
            </div>
          </div>
      <!-- </div> -->
          <!-- <div class="col-md-4 d-flex align-items-stretch">
            <div class="card mb-4 shadow-sm">
              {% if product.cover %}
                <img src="{{ product.cover.url }}" class="card-img-top" alt="...">
              {% else %}
                <img src="{% static 'img/no-image.png' %}" class="card-img-top">
              {% endif %}
              <div class="card-body">
                <h6 class="card-subtitle mb-2 text-muted">{{ product.category }}</h6>
                <p class="card-text"><a href="{% url 'product-detail' product.id %}">{{ product.title }}</a> </p>
              </div>
            </div>
          </div> -->
          {% endfor %}
    </div>
        <div class="pagination">
          <span class="step-links">
              {% if page_obj.has_previous %}
                  <a href="?page=1">&laquo; first</a>
                  <a href="?page={{ page_obj.previous_page_number }}">back</a>
              {% endif %}
      
              <span class="current">
                  {{ page_obj.number }} {{ page_obj.paginator.num_pages }}
              </span>
      
              {% if page_obj.has_next %}
                  <a href="?page={{ page_obj.next_page_number }}">forward</a>
                  <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
              {% endif %}
          </span>
      </div>       
        {% else %}
          <p>No products</p>
      {% endif %}
  </div>
</div>
{% endblock %}

Final_projektas/mystore/main/templates/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container_brand">
    <div class="home_div">
        <div class="content-section">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
        <!-- <div class="media">
            <img class="rounded-circle account-img" src="{{ user.profile.photo.url }}">
            <div class="media-body"> -->
            <h2 class="account-heading">{{ user.username }}</h2>
            <p class="text-secondary">{{ user.email }}</p>
            </div>
        </div>
        <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Your profile info</legend>
                    {{ u_form|crispy }}
                    {{ p_form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">update your profile</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

Final_projektas/mystore/main/templates/register.html
{% extends "base.html" %}

{% block content %}

    <div class="container register">
        <h3>Registration</h3><br/>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                <input name="username" type="text" class="form-control" id="username" aria-describedby="usernameHelp">
                <small id="usernameHelp" class="form-text text-muted">Up to 150 symbols</small>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Email</label>
                <input name="email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <small id="emailHelp" class="form-text text-muted">Email required for password reset</small>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input name="password" type="password" class="form-control" id="password" aria-describedby="pwdHelp">
                <small id="pwdHelp" class="form-text text-muted">Password cannot have less than 8 symbols.</small>
            </div>
            <div class="form-group">
                <label for="password2">Repeat password</label>
                <input name="password2" type="password" class="form-control" id="password2" aria-describedby="pwd2Help">
            </div>
            <button type="submit" class="btn btn-primary register-button">Register</button>
        </form>
        <p>If you have already registered <a href="/login"><strong>please log in.</strong></a></p>
    </div>

{% endblock %}

Final_projektas/mystore/main/templates/search.html
{% extends "base.html" %}

{% block content %}
  <h1>Search "{{query}}" results:</h1>
  </br>
  {% if products %}
  <ul>
    {% for product in products %}
      <li>
        <a href="{% url 'product-detail' product.id %}">{{ product.title }}</a> ({{brands.name}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Nothing found</p>
  {% endif %}

  {% endblock %}